    <div class="footer">
        <div class="row m-5 bg-dark text-white">
            <div class="col-md-4 text-center">
            <a href="#">FAQ</a>
            </div>
            <div class="col-md-4 text-center">
            Todos os Direitos Reservados
            &copy; <?=date('Y')?>
            </div>
            <div class="col-md-4 text-center">
            <a href="#" class="">Contato</a>
            </div>
        </div>
    </div>
        <!-- javascript -->
        <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
    </body>
</html>