<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#"><img src="/img/capcom-logo.png" class="navbar-logo"></a>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-link active" href="/">Home</a>
      <a class="nav-link" href="about.php">Sobre</a>
      <a class="nav-link" href="purchase.php">Comprar</a>
    </div>
  </div>
</nav>